/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings/index'
import { Route as MeetingsMeetingIdRouteImport } from './routes/meetings/$meetingId'
import { Route as ApiMeetingsMeetingIdChatRouteImport } from './routes/api/meetings/$meetingId/chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdRoute = MeetingsMeetingIdRouteImport.update({
  id: '/meetings/$meetingId',
  path: '/meetings/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsMeetingIdChatRoute =
  ApiMeetingsMeetingIdChatRouteImport.update({
    id: '/api/meetings/$meetingId/chat',
    path: '/api/meetings/$meetingId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/api/meetings/$meetingId/chat': typeof ApiMeetingsMeetingIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/meetings': typeof MeetingsIndexRoute
  '/api/meetings/$meetingId/chat': typeof ApiMeetingsMeetingIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/api/meetings/$meetingId/chat': typeof ApiMeetingsMeetingIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/meetings/$meetingId'
    | '/meetings/'
    | '/api/meetings/$meetingId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/meetings/$meetingId'
    | '/meetings'
    | '/api/meetings/$meetingId/chat'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/meetings/$meetingId'
    | '/meetings/'
    | '/api/meetings/$meetingId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MeetingsMeetingIdRoute: typeof MeetingsMeetingIdRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  ApiMeetingsMeetingIdChatRoute: typeof ApiMeetingsMeetingIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId': {
      id: '/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof MeetingsMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings/$meetingId/chat': {
      id: '/api/meetings/$meetingId/chat'
      path: '/api/meetings/$meetingId/chat'
      fullPath: '/api/meetings/$meetingId/chat'
      preLoaderRoute: typeof ApiMeetingsMeetingIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeetingsMeetingIdRoute: MeetingsMeetingIdRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  ApiMeetingsMeetingIdChatRoute: ApiMeetingsMeetingIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
